// <auto-generated />
using DTLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DTLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250914191811_git inital")]
    partial class gitinital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DTLayer.Entities.Items", b =>
                {
                    b.Property<short>("itemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("itemID"));

                    b.Property<string>("itemName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar");

                    b.Property<short>("specilizeID")
                        .HasColumnType("smallint");

                    b.HasKey("itemID");

                    b.HasIndex("specilizeID");

                    b.ToTable("items");
                });

            modelBuilder.Entity("DTLayer.Entities.Specilzeations", b =>
                {
                    b.Property<short>("specilizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("specilizeId"));

                    b.Property<string>("specilizeName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar");

                    b.HasKey("specilizeId");

                    b.ToTable("specilzeations");
                });

            modelBuilder.Entity("DTLayer.Entities.Items", b =>
                {
                    b.HasOne("DTLayer.Entities.Specilzeations", "specilize")
                        .WithMany("Items")
                        .HasForeignKey("specilizeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("specilize");
                });

            modelBuilder.Entity("DTLayer.Entities.Specilzeations", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
